print("Welcome to Burn Bot! Answer the questions below and prepare to be roasted")
name = input("What's your name?")
age = input("How old are you?")
animal = input("What is your favorite animal?")
hobby = input("What is your favorite hobby?")
dessert = input ("What's your favorite dessert?")
print("Processing your oversharing...Generating Judgemnts...")
print(f"So, {name}!")
print(f"so you are {age} years old? Sure, but do you actually act like it? ")
print(f"your favorite animal is {animal} Wow, that's totally not basic at all... ")
print(f"In your free time, you like to {hobby}... at least you are consistant with being predictable. ")
print(f"You enjoying eating {dessert}... said you were {age}...sure proved my point ")
print(f"Thanks for oversharing {name}! Don't worry, your data might not be sold to aliens!")
      